### ISSUE TITLE
select filter with essentials build

### ISSUE THREAD

**Issue by 89z** [GyanD/codexffmpeg#19]
With this file [1], if I use this program [2], and this command:

~~~sh
ffmpeg -i crushed-between-two-portals.mp4 -vsync vfr -vf "select='eq(pict_type,I)'" %d.jpg
~~~

I get expected result. However if I use this program [3] instead, I get this:

~~~
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
~~~

1. https://f002.backblazeb2.com/file/ql8mlh/crushed-between-two-portals.mp4
2. https://github.com/GyanD/codexffmpeg/releases/download/4.4/ffmpeg-4.4-full_build.7z
3. https://github.com/GyanD/codexffmpeg/releases/download/4.4/ffmpeg-4.4-essentials_build.7z

**Comment by 89z** [comment]
As a workaround, I am switching to this:

https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-04-11-12-36/ffmpeg-n4.4-4-gacb339bb88-win64-lgpl-4.4.zip

as it works as well, and is actually has a smaller extracted size.

**Comment by GyanD** [comment]
The input has an AV1 stream. The essentials build only has libaom linked and apparently libaom's decoder doesn't flag output frames correctly. The full build has dav1d also linked which is autoselected as it has higher priority and it does mark frames correctly. So this is a limitation of the decoder.

My full builds are larger since they link more libraries.

**Comment by 89z** [comment]
This was fixed here: https://github.com/FFmpeg/FFmpeg/commit/8b954a727a74c5adaea9d8a1fc490c12cd4e0db8

so should be able to use Essentials build on the next release

**Comment by 89z** [comment]
This is now fixed as of this release

https://github.com/GyanD/codexffmpeg/releases/tag/2021-04-18-git-d43b26b30d
